image: webhippie/golang
pipelines:
  branches:
    master:
      - step:
          name: Build and release
          script:
            - go get -v -t ./...
            - go build -o licence-checker check.go
            - ls -l
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"licence-checker"
