image: golang:alpine
pipelines:
  branches:
    master:
      - step:
          name: Build and release
          script:
            - go get github.com/google/licensecheck
            - go build
            - export artifact=licence_checker
