image: golang:alpine
pipelines:
  branches:
    master:
      - step:
          name: Build and release
          script:
            - apk add git
            - go get github.com/google/licensecheck
            - go build
            - ls -l
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"licence-checker"
