image: golang:alpine
pipelines:
  branches:
    master:
      - step:
          name: Build and release
          script:
            - apk add git
            - go get github.com/google/licensecheck
            - go build
            - pipe: atlassian/bitbucket-upload-file:0.1.2
              variables:
                BITBUCKET_USERNAME: $BB_AUTH_USERNAME
                BITBUCKET_APP_PASSWORD: $BB_AUTH_PASSWORD
                FILENAME: "licence_checker"
