name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    container: webhippie/golang
    steps:
      - uses: actions/checkout@v3

      - name: Work around git permission issue
        run: |
          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
          git config --global --add safe.directory /__w/$dname/$dname
        shell: sh

      - name: Build licence checker
        run: |
          go get -v -t ./...
          go build -o licence-checker ./...

      - name: Test licence checker
        run: |
          go test ./...


