name: Upload Release Asset

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    container: webhippie/golang
    steps:
      - uses: actions/checkout@v3

      - name: Work around git permission issue
        run: |
          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
          git config --global --add safe.directory /__w/$dname/$dname
        shell: sh


      - name: Build licence checker
        run: |
          go get -v -t ./...
          go build -o licence-checker ./...

      - name: Test licence checker
        run: |
          go test ./...

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            licence-checker


